
### GET ALL Orders

GET http://localhost:4200/aggregator/orders?manufacturer=NTUC

###

GET http://localhost:4200/aggregator/orders?sortBy=createdOn

### GET Order by id

GET http://localhost:4200/aggregator/orders/99

### POST Orders

POST http://localhost:4200/aggregator/orders
Content-Type: application/json

{
  "id": 3,
  "lineItems": [
    {
      "productId": "43134",
      "name": "Potato Chips",
      "manufacturer": "NTUC",
      "country": "SG",
      "quantity": 5,
      "unitPrice": 1,
      "total": 5
    },
    {
      "productId": "43389",
      "name": "Charger",
      "manufacturer": "Apple",
      "country": "SG",
      "quantity": 1,
      "unitPrice": 20,
      "total": 20
    }
  ],
  "status": "NEW",
  "netTotal": 5
}

### PUT Order

PUT http://localhost:4200/aggregator/orders/3
Content-Type: application/json

{
  "status": "NEW",
  "netTotal": 25
}

### DELETE Order

DELETE http://localhost:4200/aggregator/orders/99